name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Fix Git Safe Directory Issue
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Clean up Git Submodule Configurations
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --local --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --local --unset-all core.sshCommand || true

      - run: npm install
      - run: npm run build --if-present
     
      - name: change directory
        run: cd /home/leo/runners/listing-bot/_work/nft-listing-bot/nft-listing-bot
      - run: pm2 restart listing-bot
